### ISSUE TITLE
[FEAT] Create "hotspot" reports

### ISSUE THREAD

**Issue by mattyweb** [hackforla/311-data#1034] opened 2021-03-21 18:05 UTC
# Description

I added a density-based clustering (DBSCAN) endpoint that get the clusters by type for the past year:
https://dev-api.311-data.org/geojson/hotspots?type_id=2&start_date=2020-03-21

It returns a GeoJson feature which can be mapped like this:
    {
      "type": "Feature",
      "properties": {
        "council_name": "Woodland Hills-Warner Center",
        "council_id": 98,
        "hotspot_id": 0,
        "count": 115
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -118.57104099577371,
          34.17170469474082
        ]
      }
    },

This can be used, for instance, to show the coordinates of the "hotspots" for a particular issue. For instance, what locations have the most repeated complaints for graffiti, encampments, illegal dumping, etc.

## Action Items

The goal would be to either add an option to the map to show these points or create a dashboard that displays them. Ideally, the report would use the cluster counts to show the EXTREME hotspots (marked in red in the report example below).

## Resources

https://en.wikipedia.org/wiki/DBSCAN

![image](https://user-images.githubusercontent.com/10199792/111915780-33afef80-8a35-11eb-8278-2679f108c8f8.png)

**Comment by EchoProject** [comment] 2021-10-15 02:00
Matt has made an endpoint on the API which returns the geojson. Current plan is to create new mapbox layer that renders the geojson feature. Should be toggleable at bottom right of map.

**Comment by nichhk** [comment] 2022-08-09 01:33
Closing this as a dupe of #1279.

**Closed by nichhk** 2022-08-09 01:33 UTC
Labels: Enhancement, Role: Frontend, Size: 5pt, P-feature: Map
