### ISSUE TITLE
Desktop Menu redesign

### ISSUE THREAD

**Issue by elizabeth-ux** [hackforla/311-data#1157] opened 2021-11-12 04:01 UTC
### Overview
Redesign desktop menu to remove filters/settings option and include those options as part of the menu

### Action Items
- [x] Remove Filters cog
- [x] Incorporate filters/settings options into menu as accordion 
- [ ] Incorporate a District tab
- [ ] Remove boundary drop-down from Address tab
- [ ] Add boundary drop-down to District tab
- [ ] Omit information box 
- [ ] Make council searching more user-friendly on Map [reference issue #1306](https://github.com/hackforla/311-data/issues/1306)

### Resources/Instructions
Add screenshots or link to Figma file

**Comment by elizabeth-ux** [comment] 2021-12-10 00:47
This is what I have so far. 
![9EE87F98-07BF-4E29-ABAE-7952AAF85DE5](https://user-images.githubusercontent.com/20293568/145498235-556508a6-bcc4-4f95-a162-cbf37a0f4cf4.jpeg)
Need to add the colors to the requests and fix spacing on the menu. I alphabetized the requests as well.

**Comment by elizabeth-ux** [comment] 2021-12-27 03:44
I've completed the menu redesign. I made a copy of the dark color styles used and placed it in the Design Studio so it's easier to see where the request type colors came from. [https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=2775%3A7702](url)

**Comment by elizabeth-ux** [comment] 2022-06-20 04:29
Per discussion with @EchoProject made following changes to the menu.

I added a scroll bar, expanded the menu to also include request type when users first see and information box is separate from menu - can be a pop-up.
District can be an option under boundaries.
![scroll expanded](https://user-images.githubusercontent.com/20293568/174524655-a8aec1c4-50e9-416f-aa3c-6578442d41cc.png)
![Menu](https://user-images.githubusercontent.com/20293568/174524702-5f5bf661-f8da-4396-921e-8ec144c1cbea.png)
![Info Box](https://user-images.githubusercontent.com/20293568/174524718-7488a760-1628-499c-8d9b-f9e5c2a563b1.png)

**Comment by melissahermes99** [comment] 2022-08-11 23:37
Elizabeth and I have developed two new versions of a horizontal bar map key. 

![image](https://user-images.githubusercontent.com/97048386/184259670-27d5236f-bccf-4be4-b599-40890f35649b.png)

**Comment by EchoProject** [comment] 2022-09-15 01:55
@elizabeth-ux @melissahermes99 @nichhk 
Confirming that this iteration is the final decision (at least until post-launch) menu re-design. Once confirmed, we can close this issue and eng can take over for dev.

**Comment by nichhk** [comment] 2022-09-15 23:10
@elizabeth-ux @melissahermes99 , could you share a figma link for the final decision? Thanks!

**Comment by melissahermes99** [comment] 2022-09-15 23:14
Of course! The final version of the map is located on [the Version 2_Iterations page](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=1009%3A1004) at the very bottom. I believe this is the finalized version for now. I'll reach out to Elizabeth directly on Slack to verify.

**Comment by melissahermes99** [comment] 2022-09-15 23:22
![image](https://user-images.githubusercontent.com/97048386/190525202-174b6974-9b47-4b9a-b0df-45b7dea8b18a.png)
We've agreed that is the final version for now.

**Comment by EchoProject** [comment] 2022-09-22 03:02
@nichhk it looks like we're good to go with the above design and the figma link is in the comment above the design. Let us know what you need from on our end.

**Comment by nichhk** [comment] 2022-09-22 03:10
Thanks! I'm closing this issue, and opened #1370 for Edwin to implement the redesign.

**Closed by nichhk** 2022-09-22 03:10 UTC
Labels: Role: Frontend, Size: 5pt, P-feature: Map
