### ISSUE TITLE
Only use first 7 chars of sha for docker tags

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#358] opened 2020-03-04 01:57 UTC
#Description
Docker images are tagged with the entire sha, this isnt really necessary, they should only be tagged with the first 7

## Action Items
  - Update Publish X image workflows to only tag with the first 7 chars of the git sha

**Comment by jmensch1** [comment] 2020-06-11 16:58
duplicate of #402

**Closed by jmensch1** 2020-06-11 16:58 UTC
Labels: Workflows
