### ISSUE TITLE
Remove dashboard from website menu

### ISSUE THREAD

**Issue by ahmedsalah0130** [hackforla/311-data#1627] opened 2023-11-20 01:45 UTC
# Design To Engineering Hand Off

### Overview
Ticket for tracking designs submitted to engineering, discussion around implementation of designs.

### Description of Requested Change

We need to remove the dashboard from the website menu. 

### PM Action Items

- [x] Fix Title
- [x] Update 'Feature Description'
- [x] Add assignees (Design Lead, Engineering Lead, Assigned PM)
- [x] Assign a Milestone
- [x] Assign a Feature label
- [x] Remove label 'Milestone: Missing'
- [x] Add to Project Board

# Design

### Design Action Items
- [ ] fill in 'Section Name' in Figma Resources
- [ ] update image url and remove markdown tags
- [ ] Update 'Design Issue(s)' with list of relevant issues with role `role: UI/UX Design`

### Figma Resources
- [Link to Figma File](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?type=design&node-id=4081%3A9245&mode=design&t=PTDbT1wUuq0S7f2W-1)
- Page Name:⭐⭐⭐ V1.2 HAND-OFF
- Section Name: <TODO>

### Screenshot of Finalized Designs

Image which helps engineer understand where to look. (Replace the url and remove the markdown tags)

```html
<img src=https://github.com/hackforla/311-data/assets/6414668/6895f56b-0048-4dab-a351-d43b03c89737 width="20%"/>
```

### Design Issue(s)
```
Replace this text with a bulletted list of issues
```
# Engineering

### Engineering Action Items
- [ ] Review 'Useful Notes for Figma' below
- [ ] Locate section on 311 Data Figma
- [ ] Create and list engineering tickets

### Useful Notes for Figma
The file describes the overall Figma page. There is one Figma file for the team, which is the `311_Data_UXUI` file. The page is the location of designs within the file, selected via the left-hand-side as a table of contents. The section name is the title of a particular section of the page. The section will encompass all relevant info needed to complete this request. 

### Engineering Issue(s)

```
Replace this text with a bulletted list of issues
```

### Resources
```
Replace this text with a bulletted list of resources that might be useful to engineers or designers
```

**Comment by ryanfchase** [comment] 2024-01-18 20:35
Ok I know that Bonnie said that this needs to go to UIUX design, but I actually think it can just be a very thin engineering ticket. I'm going to fix this ticket tonight at the PM meeting.

**Comment by ryanfchase** [comment] 2024-01-20 19:58
PM team is migrating the design to eng hand off tickets to become epics. Moving to New Issue Approval in the meantime.

**Comment by ryanfchase** [comment] 2024-01-20 20:51
Closing this as a duplicate of #1624

**Closed by ryanfchase** 2024-01-20 20:51 UTC
Labels: Role: Frontend, Size: 1pt, p-feature: Dashboard, Design-To-Engineering Hand Off, draft
