### ISSUE TITLE
[PAGE] Reports Layout/Pages (Dash)

### ISSUE THREAD

**Issue by mattyweb** [hackforla/311-data#963] opened 2021-02-22 04:31 UTC
# Description

- Should be the equivalent of this: https://311-data.org/comparison
- Should have menu item(s) in Header: probably a menu with a list of the available reports

**Comment by adamkendis** [comment] 2021-03-12 02:22
Closing as duplicate of #837

**Closed by adamkendis** 2021-03-12 02:22 UTC
Labels: UI/UX, data, frontend
