### ISSUE TITLE
Investigate relationship between NC socioeconomic class and 311 requests

### ISSUE THREAD

**Issue by nichhk** [hackforla/311-data#1278] opened 2022-07-08 21:33 UTC
### Overview
This can be an interesting data science deep dive.

* Do wealthier or more socioeconomically advantaged NCs make more 311 requests?
* Do wealthier or more socioeconomically advantaged NCs have their 311 requests handled more quickly?

### Action Items
- [ ] Find data on socioeconomic class per NC, or other appropriate proxies
- [ ] Find correlation between class and number of 311 requests made
- [ ] Find correlation between class and 311 request time to close

**Comment by nichhk** [comment] 2022-07-21 19:09
The LA Times recently published an [article](https://www.latimes.com/california/story/2022-07-18/thousands-homeless-sears-boyle-heights-opposition) about a plan to make Boyle Heights' Sears building into a homeless services hub. Some Boyle Heights residents don't like this plan:

> Others lamented that basic services they’ve demanded from city and county officials — street cleaning, affordable housing and better security — continued to be neglected, while homelessness has taken center stage.

It would be great to investigate this using 311 Data.

**Comment by JACKIEKWON** [comment] 2022-07-28 03:08
I am using [311 Request Data](https://data.lacity.org/City-Infrastructure-Service-Requests/MyLA311-Service-Request-Data-2022/i5ke-k6by) to get the request count and request completion time for each NC. 

I was planning to use [Census Population/Demographic Data by NC](https://data.lacity.org/Community-Economic-Development/Census-Data-by-Neighborhood-Council/nwj3-ufba), using the in-poverty population percentage as a measure of socioeconomic status, but 85 of 97 NCs' % population in poverty is > 98% so I'm not sure if it's reliable [Census_Data_by_Neighborhood_Council - Populations.xlsx](https://github.com/hackforla/311-data/files/9204940/Census_Data_by_Neighborhood_Council.-.Populations.xlsx). Will need to find a different proxy for socioeconomic status.

**Comment by nichhk** [comment] 2022-07-28 22:40
Yeah that data looks really unreliable. I see that there's a way to contact the dataset owner on the [website](https://data.lacity.org/Community-Economic-Development/Census-Data-by-Neighborhood-Council/nwj3-ufba). Could you share your findings with them and see if they respond?

**Comment by nichhk** [comment] 2022-07-29 02:25
Jackie to focus on social aspects and Michael on economic aspects for now.

**Comment by joshuayhwu** [comment] 2022-07-30 03:06
Wanted to add some thoughts on some ways to explore this issue, feel free to ignore this if you feel there are other approaches that you think work best.

Before that, let's clarify the objective of this deep dive from my understanding:
- Investigate the relationship between NC socioeconomic status and 311 requests; attempt to reveal any pattern between the two "datasets" 
- If there are any relationships, what are some actionable items we can reccomend to neighborhood councils to improve the existing situation

To deep dive into this problem, we need to decide on a measure of socioeconomic status. Unfortunately, we are fairly limited on the available data at the neigbhorhood council level, for instance, we get [median income](https://maps.latimes.com/neighborhoods/income/median/neighborhood/list/), [4 year degrees](https://maps.latimes.com/neighborhoods/education/four-year-degree/neighborhood/list/), [health profiles](http://ph.lacounty.gov/ohae/cchp/healthProfileExcel.htm). Ultimately, many of these data sources need us to either web scrape or proactive;y reach out to the relevant departments for raw data files.

Below are some steps we could consider when conducting this analysis:
- Decide on one / multiple measures of socioeconomic status, preferably once that have data avaialble at the neigbhorhood council level (e.g. education level, median household income, health profiles, [water quality](https://nwis.waterdata.usgs.gov/ca/nwis/qwdata/?site_no=11092450&agency_cd=USGS&inventory_output=0&rdb_inventory_output=file&TZoutput=0&pm_cd_compare=Greater%20than&radio_parm_cds=all_parm_cds&format=html_table&qw_attributes=0&qw_sample_wide=wide&rdb_qw_attributes=0&date_format=YYYY-MM-DD&rdb_compression=file&submitted_form=brief_list), [household size](https://maps.latimes.com/neighborhoods/household-size/neighborhood/list/), 
- Reach out to relevant agencies to get access to datasets (USC has a web app called [Neighborhood Data For Social Change](https://map.myneighborhooddata.org/) that might have some interesting data sources you can reach out and access)
- Decide on the specific granularity of data (e.g. NC level, specific decimal places of Lat/Long ) then aggregate the data to find the sum or average number of requests, do the same with the socioeconomic data so that it's consistent on both sides
- Join the data together on that granularity so that you have one resulting large dataset
- Conduct statistical analysis as you desired. Regression analysis is probably the simplest and most interpretable form. Pick one of the socioecoomic mesaaures as your dependent variable on it, and see what the relationships are
- Consider reverse causation, it could be possible some variable such as a more affluent neighorhood would have fewer 311 requests such as graffiti.
- After the analysis, what are some actionable insights? What areas could the NCs improved upon? If there are none, what are the trends based on historic data?
- Find a way to communnicate your results, whether it's through dashboards, slides, or even jupyter notebook.

Again, feel free to ignore this - I hope this can serve as a reference and at least help generate some ideas.

**Comment by Michaeldavidng** [comment] 2022-08-08 22:01
Found a good, reliable source for demographic data. Only problem is that the data is somewhat on the old side, seems like 2008 numbers. Better than nothing though.

**Comment by Michaeldavidng** [comment] 2022-08-08 22:18
Working on a spreadsheet that list the median income for each neighborhood council. I'm putting a column of the URL of where i got the data from and another column that list the relevant date (i.e. Median income as of 2008 dollars). 

Will put on google sheets by Thursday.

**Comment by Michaeldavidng** [comment] 2022-08-09 17:57
Found other good sources for demographic data.
https://www.pacificurbanism.org/publications/neighborhood-council-census-data
the link above is good because it obtain its data from the 2015 US census. While a little bit old, at least the source is reliable.

other sites are:
https://www.weichert.com/search/community/neighborhood.aspx?hood=61301

I think others might be interested in the link below because it has a cool map 
https://lapublic.space/nc/empowerment-congress-southwest

I know none of you care what I comment but in case it does help someone, I'm good.

**Comment by nichhk** [comment] 2022-08-09 18:13
Hey Michael thanks for looking for these data sources! I agree that the Pacific Urbanism source looks pretty reliable. It does look like it only has data for 97 NCs--there are actually 99 now. But I imagine that their data would be a good starting point. It's interesting that the PDF says it was prepared for "the City of Los Angeles Department of Neighborhood Empowerment"--if I'm not mistaken, we are explicitly partnered with them. It would be interesting to reach out to to them and see if they have more up-to-date data. @EchoProject.

I'm sorry I haven't been able to respond more promptly Michael. Not sure if it helps, but I do read all of your comments, and I really appreciate your hard work on this! I'll try to respond faster in the future.

**Comment by Michaeldavidng** [comment] 2022-08-09 23:00
https://docs.google.com/spreadsheets/d/1iw-8FvFrlTpcD2s7yiqiBQLBqhxvPOLGjpy6G5aHyFc/edit?usp=sharing

created spreadsheet listing Median Household Income per Neighborhood council.

Majority of data came from: https://www.pacificurbanism.org/publications/neighborhood-council-census-data which itself drew the data from the US census and governmental survey; in other words, the data is reliable. Problem was that the data is only up to 2015. Don't know of another reliable source to get data from a later date so this seems like the closest.

Thought: maybe pull 311 data specifically for the year 2015?

will utilize new spreadsheet in conjunction with 311 data spreadsheet and to pull any correlation.

**Comment by nichhk** [comment] 2022-08-11 17:16
Yeah, try pulling 2015 311 request data if possible. Looks good!

**Comment by Michaeldavidng** [comment] 2022-08-12 02:37
Did overview analysis comparing wealth to 311 request.
https://public.tableau.com/app/profile/michael.david.ng/viz/Wealthvs_311request/Story1
https://youtu.be/BlekqoSABcs
on the youtube presentation there is slight error. the date difference column was created using "created date" and "close date" which was done correctly in the presentation but I mentioned a different date rather that "created date" in the video.

Feedback.
Josh = First bar chart. play with filters. try to find additional insights. in other words, go deeper with the exploration.
Liz = very last regression chart. remove outliers because data seems very close. See if outliers are removed if it somehow improves correlation.

Future Steps:
will incorporate Josh's and Liz's feedbacks.

**Comment by Michaeldavidng** [comment] 2022-08-16 18:23
8/16/2022 - zyzz
I've gone ahead and updated the above tableau link with additional tabs in accordance to the previously provided feedback. Still in rough draft stages but hoping to polish it by Thursday.

Found a good demographic source from the American Community Survey. I'm thinking about using it for when I analyze the social aspect of socioeconomic whatever.

https://drive.google.com/drive/folders/1uupIXEGEC8UlFOCQiyIPH9q7JmETn_Cx

**Comment by Michaeldavidng** [comment] 2022-08-17 23:12
8/17/2022
_Social aspect_
found 2010 census data that list demographics into each neighborhood council. 
https://data.lacity.org/Community-Economic-Development/Census-Data-by-Neighborhood-Council/nwj3-ufba

unlike the other datasets like those I posted yesterday, they aren't based on estimates and the data is fitted to each neighborhood council specifically.

I'm going to compare the 2010 census data against the 2015 311 service request dataset simply because I was unable to find a dataset earlier than 2015. While not exactly an apple-to-apple comparison, my rationale is that population changes take a long time to happen so whatever subtle change happen shouldn't make too deep of an impact.

https://data.lacity.org/City-Infrastructure-Service-Requests/MyLA311-Service-Request-Data-2015/ms7h-a45h\

Expecting a prototype for Neighborhood council vs social by 24th August.

**_Economic_**
Still working on preparing for the economic dataset that will address both Josh and Liz's feedback. zyzz

**Comment by joshuayhwu** [comment] 2022-08-18 01:14
@Michaeldavidng thanks for the update! I notice there is also 2020 census data available [here](http://www.laalmanac.com/population/po24la.php). Would it be possible to use 2020 311 data instead? 

Thanks for the estimate!

**Comment by Michaeldavidng** [comment] 2022-08-18 01:23
@joshuayhwu that is good idea. I actually initially tried to use the data set but what I noticed is that the almanac dataset has neighborhoods that aren’t in the neighborhood council list.

additional some neighborhood councils aren’t on the almanac dataset.

this led me to conclude that it’s not 1-to-1.

to make it work, I would have to find how the almanac neighborhood geographically fits into the neighborhood council area.

I look into in more just to be sure but this was just my initial assessment of the almanac dataset

**Comment by priyakalyan** [comment] 2022-08-18 01:46
@Michaeldavidng @joshuayhwu Michael is right, the census data [here](http://www.laalmanac.com/population/po24la.php) does not correspond to LA NCs. Here is the [map](https://geohub.lacity.org/datasets/d6c55385a0e749519f238b77135eafac_0/explore?location=34.020320%2C-118.410084%2C10.43) with the cities for which they have determined the population using the census 2020 data. This map is totally different from the NC one.

**Comment by joshuayhwu** [comment] 2022-08-18 13:28
@Michaeldavidng @priyakalyan thanks for the clarification! I was wondering if the census data was using the older versions of the boundaries? If so, would 2019 311 requests be more appless to apples?

**Comment by priyakalyan** [comment] 2022-08-18 16:24
@joshuayhwu @Michaeldavidng This resource -https://drive.google.com/drive/folders/1uupIXEGEC8UlFOCQiyIPH9q7JmETn_Cx posted by Michael is really very useful. The population and other demographics related analysis has been compiled by EmpowerLA.org using the census 2020 data and recent LA NC boundary (99 NCs). 

I have been trying to reach the person who put together the sheet- Julien Antelin. He got back to me immediately saying that he does not work there anymore and he mentioned couple of people who can help me with my queries. I will update as soon as I hear back from any of them. 

Regarding the population analysis here- http://www.laalmanac.com/population/po24la.php, they have not used the old NC boundary. Check out the description and summary - https://geohub.lacity.org/datasets/lahub::la-times-neighborhood-boundaries/about. They have 114 records in total and they are mainly focusing on city boundary as opposed to NC boundary.

**Comment by Michaeldavidng** [comment] 2022-08-19 22:01
8/18/2022
Presented my findings concerning feedback to Josh and Liz's concerns.
You can see my findings here: https://youtu.be/k-fdW0x_V5Y
My internet kind cra**ed out at the end of the video. Below is the image I was refering to at the end of the video.
![image](https://user-images.githubusercontent.com/105311370/185712000-55cbb86a-c03c-4055-a09a-2b09a14236dc.png)

Additionally,
i've decided to use: https://drive.google.com/drive/folders/1uupIXEGEC8UlFOCQiyIPH9q7JmETn_Cx
when I explore the social side of the question.
I initally had reservations because I wasn't sure if the data was precise but, in the meeting, Anupriya gave me reassuance that the data should be correct and that I should go ahead and utilize the data on that link.

Lastly, after looking through the data, the social side of the issue seems a bit more robust the economic side of the issue. Thus, I'm not sure if I can make a workable prototype by 8/24. Will still try though.

Future Steps:
move on to the social aspects of issue1278
create a workable prototype by 8/24 or 8/31

**Comment by Michaeldavidng** [comment] 2022-08-20 16:06
8.20.2022

Currently making a spreadsheet version of https://drive.google.com/drive/folders/1uupIXEGEC8UlFOCQiyIPH9q7JmETn_Cx
https://1drv.ms/x/s!AvjCnhN3AazXli_aGOAE7PZnRfKG?e=xYnJNz

I'm halfway done. It's just very manually intensive. I plan to merge it onto 2018 MyLa311 request data.
Following the merge, will put it on Tableau.

**Comment by joshuayhwu** [comment] 2022-08-21 04:23
@Michaeldavidng Thanks so much for your updates! Regarding the video update:

1. This video is incredibly useful - thanks for recording that!
2. Based on your findings, what are the particular requests types we should focus on and why?
3. For the aforementioned requests types, which neighborhood councils should put more work into resolving those requests types? What are their request time to close?
4. Do you have any hypothesis on why waste water request are completed so quickly? 
5. Thanks for working on transferring the pdf files to spreadsheet. What do you think are the main problems we should tackle?

Thanks for your hard work!

**Comment by Michaeldavidng** [comment] 2022-08-22 17:46
_Question 2_:
To be honest, which request type I would focus on would depend on the context. if, let's say, we are concerned about environment, electronic waste and water waste would be a priority.

For me, if I was governor of California, I would prioritize all of them except graffiti removal due to low count, feedback (which isn't a request type), Other. Below are my reasons why. Bulky items, electronic and household appliance removal are not threats

Dead Animal Removal = many have 200 animals killed per year, which to me is excessive

Homelessness = Keep your political opinions to yourself. homeless encampments can and often does create issue in a society. regardless of the number, these encampments can create a threat.

illegal dumping = regardless of number, the act is illegal and thus should be crackdown.

multiple and single streetlights = regardless of number, a broken streetlights encourage criminal activity and should be considered a threat.

**_Question 3_**
Dead animal Removal = empowerment congress southeast has significantly higher dead animals than the rest. takes 1.02 days but the sheer amount is disconcerting.
Downtown LA. why does it take more than a month to get rid of a dead animal?

Homelessness 
With bigger urban areas such as Downtown LA and hollywood, homelessness is to be expected.
however, it takes over 200 days for Harbor City and Olympic Park to address homeless encampments, which is wrong.

illegal dumping
empowerment congress southeast significantly more than most. 8.6 days
downtown LA takes more than 30 days

multiple streetlight
greater wilshire = sheer amount. 16.8 days
silver lake NC = 150 days

Single Street
Downtown LA = sheer amount. 22.56 days
Foothill trails district NC & MacArthur Park = more than 50 days

**_Question 4_**

My guest is that they spend a warning via phone or email as soon as a request comes in. maybe they would send someone to reprimand them when notified.

**_Question 5_**
honestly I don't know. I highly doubt that the racial aspect is going to yield much data regarding problems.

**Comment by Michaeldavidng** [comment] 2022-08-23 19:19
So, I've made a prototype of sorts:
https://public.tableau.com/app/profile/michael.david.ng/viz/Demographicsvs_LA311request/Agetotal

it's just a rough draft though. I have some concerns because the numbers seem a little strange so I'd like for us to talk about it on Wednesday during the meeting.

As a side snide comment, I'm not really liking how the meeting were shifted earlier to Wednesday.

**Comment by nichhk** [comment] 2022-08-24 01:13
FYI, Jackie is no longer working on the project since she's starting a new job.

Thanks for all these artifacts, Michael! I watched your video, and I noticed that some of the income values were really high, 210M in one case. Could you share how the income value was obtained?

I'll also add that controlling for population should give us more confidence in these analyses. E.g., it's possible that some of the NCs that have a lot of requests just have more people. I see that you have the population data in your new prototype, but I couldn't tell whether it's being used.

**Comment by Michaeldavidng** [comment] 2022-08-24 21:34
> Thanks for all these artifacts, Michael! I watched your video, and I noticed that some of the income values were really high, 210M in one case. Could you share how the income value was obtained?

I know the slide your talking about. For the second video, I accidently left it as Sum of Median income rather than Average Median income. 

I should mentioned that either way the overall conclusion for each slide in the 2nd video hasn't change. The conclusions of the non regression slides on the 2nd video were not based on income but rather observations of problems that I notice. i.e. which neighborhood conclusion were fixing each request type too slow or which had an unusually large count of each request type.

Fortunately for me, the regression slides (of the 2nd video) did use the correct average median income instead of sum.

**_Population_**
As for population, I do have a field for it in the upcoming tableau thing that I will show later today on Wednesday.

I'm hoping to get feedback on it because what I made is ugly and I need info on the specifications that people need.

**Comment by joshuayhwu** [comment] 2022-08-27 04:26
Hey Michael, thanks so much for your hard work both on this particular issue and the regular updates! 

Do feel free to take your time on this. Regarding the feedback on the length of the presentation, I reccomend focusing on a couple relevant points / visuals you want to present as that can help consolidate the main question you are trying to answer. In doing so, you help the audience perceive the data in some meaningful way. Just my two cents.

Feel free to present work in progress during our meetings :) These deep dives are intended to be short to long term projects. So do take your time. Again, appreciate the hard work you put it to copy the pdfs onto spreadsheet, making comprehensive summary videos, and updates on this issues. This is extremely helpful for us to generate insights on this issue.

Let us know how we could best help!

**Comment by nichhk** [comment] 2022-08-29 18:50
+1 to what Josh said. Your work here is exemplary, Michael--I really like your updates, and I can tell how much effort you're putting into them.

Like Josh said, please take your time. At the end of the day, your health and wellbeing is the most important thing, and I want everyone to feel comfortable prioritizing those!

**Comment by Michaeldavidng** [comment] 2022-08-30 21:31
Here's the first video concerning population: https://youtu.be/X2wmNFJvk40

again, i'm trying to make a video for each demograhpic factor, excluding income, so it might take a while.

the first video is noob friendly, meaning I designed it so that even non-data analytical people can understand it if they watch it.

I'm hoping to do age by the end of today.

**Comment by Michaeldavidng** [comment] 2022-08-31 01:25
Here's the 2nd video concerning the age demographic: https://youtu.be/tiumfg_s6YQ
Most videos will be similar to the age demographic video because I won't repeat the details of where I got my numbers or what certain jargon means like in the population video.

**Comment by Michaeldavidng** [comment] 2022-09-06 01:00
3rd video concerns race: https://youtu.be/VL1kriRq918
I purposely avoided making hypothesis for this video because there's always some idiots looking to cancel people they don't agree with.

**Comment by Michaeldavidng** [comment] 2022-09-07 01:47
4th video related to education: https://youtu.be/gJDc8wP0YNU

admittedly not my best work. I blame the heat wave but its tedious making videos too.

**Comment by Michaeldavidng** [comment] 2022-09-07 23:47
5th video related to language: https://youtu.be/0xgE7CDR-JM

Will do one more video afterwards i.e. a 6th video, it doesn't concern itself with a specific demographic factor. It will be more of a general overview. Also, it will be much less formal as will just walkthrough general observation.

**Comment by Michaeldavidng** [comment] 2022-09-08 01:02
Here's the last video: https://youtu.be/fgK1NDyFLaA

Again it was an informal video that just explored neighborhoods with interesting demographics.

**Comment by Michaeldavidng** [comment] 2022-09-08 17:03
So, I'm finished with the project and would like to close the issue but I forgot how to close it.

**Comment by joshuayhwu** [comment] 2022-09-10 15:55
@Michaeldavidng Thank you so much for making these videos! They are extremely helpful for people to digest and understand. I think this is are some interesting patterns that we could patterns based on the summary. Please correct me if I'm wrong:

1. More populus neighborhoods have a higher number of 311 requests
2. More populus neighborhoods have doesn't mean request takes longer to close 
3. Neighbhoods with older population have higher number of 311 requests
4. No correlation between age with number of 311 requests 
5. No correlation between age and length of 311 request process
6. Neighborhoods with lower education level have higher number of 311 requests *
7. Neighborhood that don't speak english well have higher number of 311 requests 

* We might need to return to this as the lower level of education is likely correlated with population. A better measure would be education / population. I'll take a look at this later on.

Once again, really appreciate you putting in so much work for this. Transcribing the data from ACS to the excel file is a huge endeavor and the videos you made have shown massive improvements from the initial presentations. Thank you for your hard work on this issue. 

The rest of the 311 team is interested in some of the work you have done. Would you be interested in doing a 5-10 minute presentation based on a summary above sometime in the next 2-3 weeks? 

Also, would you be interested in working on other issues such as parking utilization, bike share, or other problems you'd like to take a look at?

**Comment by Michaeldavidng** [comment] 2022-09-12 19:57
@joshuayhwu 
_**Conclusions about the data**_
When it comes to 311 resolution speed, most demographic factors, if not all, were either not correlated or the results were inconclusive due to a high p-value.

I think my hypothesis might have caused some confusion, so I apologize for that. Here's the conclusions I came up with based on the data

1. population is correlated with 311 request count.

2. all age groups that were younger than 65+ were correlated with 311 request count. In fact, the 65+ age group was the only age group not correlated. 

3. For Race, American Indian, Other, Bi-Racial were correlated with 311 request count. I was thinking that Other would be people who are Hispanic but didn't include themselves as either white or American Indian. That's just a theory though.

4. <9th Grade Education, High School no Diploma, High School W/ diploma, GED had strong correlation with 311 request count. Some college had moderate correlation.

5. both language groups (speaks English well vs. speaks no/little English) do have correlation with 311 request count.

_**Potential Presentation**_
I wouldn't mind doing a presentation based on the conclusions above. Though, tbh, I prefer just to create another video with the summaries above. then, you can just share the link with whoever's interested.

Let me know if that sounds like a good idea. Otherwise, I could just do a live presentation.

_**bike share**_
I've semi-recently look at a bike share dataset on Kaggle where I saw someone due regression based on weather. So, I think I might be able to help. Just send me the dataset when you have time.

**Comment by EchoProject** [comment] 2022-09-15 00:53
@Michaeldavidng This is all such amazing work, thank you! If you're up for it, It would be great for the team to see/ hear the tl;dr of your work (5-10min demo) at the meeting tonight. Let me know!

**Comment by Michaeldavidng** [comment] 2022-09-15 01:59
> @Michaeldavidng This is all such amazing work, thank you! If you're up for it, It would be great for the team to see/ hear the tl;dr of your work (5-10min demo) at the meeting tonight. Let me know!

Hey Eric @EchoProject 

Can we do it next week? I wasn't expecting tonight. 

@joshuayhwu Josh told me that it would be 2-3 weeks. Today is much too soon for me to be honest.

I need some time to prep what I'm going to say, that way it doesn't come out as an incoherent mess.

So, yeah I'll do the live presentation of all this demographic stuff but probably next week 9/21.

**Comment by joshuayhwu** [comment] 2022-09-17 19:44
@Michaeldavidng I think the team would apprecaite a live presentation as they'd likely have follow up questions.

The bike share data should be available in the [data source documentation](https://github.com/hackforla/311-data/blob/dev/misc/DataSources.md).

**Comment by Michaeldavidng** [comment] 2022-09-22 02:28
9.21.2022
did presentation as requested by Eric.
was told to indicate proportion out of total population, kinda wish that people told me earlier before I uploaded all those videos but whatever. too late now i guess.

**Comment by Michaeldavidng** [comment] 2022-09-23 20:00
9.23.2022
updated the tableau workbook to reflect proportion out of total population. 
the new, updated workbook is saved separately, see link
https://public.tableau.com/app/profile/michael.david.ng/viz/Demographicsver2/Story1

results were not good. most had r-squared too small to indicate correlation. Highest correlation was around 25% at best.
Since the results were uniformly bad, I won't make a video or do a presentation.

**Comment by nichhk** [comment] 2022-09-29 03:11
Hey Michael, thanks for working on that! I just got around to looking at it now.

If it's not too much trouble, could I make one more suggestion? I think it would be really interesting to change the y-axis to be "number of requests per person". That way, we can control for population even more effectively. To do this, you can use Anupriya's population data and for each NC, set `num_requests_per_person = num_requests / nc_population`. I'd feel pretty confident about closing this issue after doing that.

Apologies for the back-and-forth, and I appreciate your patience on this project. Unfortunately, this type of work tends to be very dependent on making many iterations before arriving at a conclusion.

**Comment by Michaeldavidng** [comment] 2022-10-05 17:44
> Hey Michael, thanks for working on that! I just got around to looking at it now.
> 
> If it's not too much trouble, could I make one more suggestion? I think it would be really interesting to change the y-axis to be "number of requests per person". That way, we can control for population even more effectively. To do this, you can use Anupriya's population data and for each NC, set `num_requests_per_person = num_requests / nc_population`. I'd feel pretty confident about closing this issue after doing that.
> 
> Apologies for the back-and-forth, and I appreciate your patience on this project. Unfortunately, this type of work tends to be very dependent on making many iterations before arriving at a conclusion.

here. I updated it based on your specifications.

**Comment by joshuayhwu** [comment] 2022-10-14 03:58
Thanks Michael! Since this issue is presented during the meeting I'll close this now.

**Closed by joshuayhwu** 2022-10-14 03:58 UTC
Labels: Role: Data Science, Size: 13pt, P-feature: Analytics
