### ISSUE TITLE
Create date range component

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#154] opened 2020-01-12 18:37 UTC
### Overview
Create date selector component, feature set below.

### Action Items
- [ ] Create reusable date selector
- [ ] Allows calendar selections or user input
- [ ] Needs to suport a start/end property when reused
- [ ] Cannot overlap. If start is 01/02/2020, then the end cannot be 01/01/2020
- [ ] Will provide its own data validation/formatting
  - [ ] Feel free to enforce what ever the time format you wish
    - [ ] Consider using moment
  - [ ] Data passed to backed should be easily parsed into a python date

### Resources/Instructions
See date range section in [this](https://www.figma.com/file/9RJJyaGAdT5hcRuv9PUMOY/311-Wireframe-v1.0?node-id=16%3A4) mock

**Comment by johnr54321** [comment] 2020-02-01 20:26
This is a duplicate of [https://github.com/hackforla/311-data/issues/166](url). Closing this ticket and assigning the other one to Adam.

**Closed** 2020-02-01 21:00 UTC
Labels: frontend
